import React, { useState } from "react";
import { Plus, LayoutGrid, List, AlertTriangle } from "lucide-react";
import type { ProjectRecord, Scope } from "@skilldock/shared";
import { useMcpList, useMcpAgents, useMcpAdd } from "../hooks/useMcp";
import { useProjects } from "../hooks/useProjects";
import { ScopeToggle } from "../components/ui/ScopeToggle";
import { EmptyState } from "../components/ui/EmptyState";
import { McpServerList } from "../components/McpServerList";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";
import { AgentsDialog } from "../components/ui/AgentsDialog";
import { useLocale } from "../contexts/LocaleContext";

export function Mcp({ onTaskStart }: { onTaskStart: (tid: string, title: string) => void }) {
  const [scope, setScope] = useState<Scope>("project");
  const { activeProject, activeProjectId } = useProjects();
  const { data: mcpListData, isLoading: isListLoading } = useMcpList(scope, activeProjectId);
  const { data: agentsData, isLoading: isAgentsLoading } = useMcpAgents();
  const addMutation = useMcpAdd();
  const { t } = useLocale();

  const [confirmState, setConfirmState] = useState<{
    isOpen: boolean;
    title: string;
    message: string[];
    confirmLabel?: string;
    onConfirm: () => void;
  } | null>(null);

  const [agentsDialogOpen, setAgentsDialogOpen] = useState(false);

  // Form states
  const [target, setTarget] = useState("");
  const [name, setName] = useState("");
  const projectWriteDisabled = scope === "project" && activeProject?.status !== "valid";

  const projectContextMessage = (project: ProjectRecord | null) => {
    if (!project) return t("projects.loading");
    return t("projects.contextLine", {
      name: project.name,
      path: project.path,
    });
  };

  const handleAddMcp = (e: React.FormEvent) => {
    e.preventDefault();
    if (!target.trim() || projectWriteDisabled) return;

    setConfirmState({
      isOpen: true,
      title: t("mcp.addServerTitle"),
      message: [
        t("mcp.addServerMessage", { target }),
        name ? t("mcp.addServerName", { name }) : t("mcp.nameAutoGenerated"),
        projectContextMessage(activeProject),
        t("mcp.addServerScope", { scope })
      ],
      confirmLabel: t("mcp.addServerButton"),
      onConfirm: async () => {
        const res = await addMutation.mutateAsync({
          target,
          name: name || undefined,
          scope,
          projectId: activeProjectId ?? undefined,
        });
        onTaskStart(res.taskId, t("mcp.addingMcp", { target }));
        setTarget("");
        setName("");
        setConfirmState(null);
      }
    });
  };

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-500">
      {addMutation.error && (
        <div className="p-4 rounded-xl bg-danger/10 border border-danger/30 text-danger text-sm flex items-center gap-3">
          <AlertTriangle size={16} />
          <span>{addMutation.error instanceof Error ? addMutation.error.message : t("common.operationFailed")}</span>
        </div>
      )}
      <header className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="flex flex-col sm:flex-row sm:items-center gap-4">
          <ScopeToggle label={t("common.scope")} value={scope} onChange={setScope} />
          <div className="min-w-0 text-xs text-text-muted">
            <div className="font-bold text-text">{activeProject?.name ?? t("projects.loading")}</div>
            <div className="truncate max-w-xs">{activeProject?.path ?? ""}</div>
            {projectWriteDisabled ? (
              <div className="mt-1 text-danger">{t("projects.invalidWriteDisabled")}</div>
            ) : null}
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            type="button"
            onClick={() => setAgentsDialogOpen(true)}
            className="px-3 py-1.5 border border-border rounded-lg text-xs font-medium text-text-muted hover:text-text hover:border-text-muted transition-colors flex items-center gap-1.5"
          >
            <LayoutGrid size={14} />
            {t("mcp.viewAgents")}
          </button>
          <form onSubmit={handleAddMcp} className="flex gap-2">
            <input
              type="text"
              placeholder={t("mcp.targetPlaceholder")}
              value={target}
              onChange={e => setTarget(e.target.value)}
              className="text-xs py-1.5 w-64 bg-surface-800 border-border rounded-lg"
            />
            <input
              type="text"
              placeholder={t("mcp.namePlaceholder")}
              value={name}
              onChange={e => setName(e.target.value)}
              className="text-xs py-1.5 w-40 bg-surface-800 border-border rounded-lg"
            />
            <button
              type="submit"
              disabled={!target.trim() || addMutation.isPending || projectWriteDisabled}
              title={projectWriteDisabled ? t("projects.invalidWriteDisabled") : undefined}
              className="px-4 py-1.5 bg-accent text-white rounded-lg text-xs font-bold flex items-center gap-2 hover:opacity-90 disabled:opacity-50"
            >
              <Plus size={14} />
              {t("mcp.addServerButton")}
            </button>
          </form>
        </div>
      </header>

      <section className="space-y-4">
        <div className="flex items-center gap-3">
          <List size={20} className="text-accent-light" />
          <h3 className="font-bold tracking-tight uppercase text-xs tracking-widest text-text-muted">{t("mcp.configuredServers")}</h3>
        </div>

        {isListLoading ? (
          <div className="h-64 rounded-2xl bg-surface-800 border border-border animate-pulse" />
        ) : mcpListData ? (
          <McpServerList result={mcpListData} scope={scope} />
        ) : (
          <EmptyState title={t("mcp.noMcpConfig")} message={t("mcp.unableToFetch")} />
        )}
      </section>

      {confirmState && (
        <ConfirmDialog
          isOpen={confirmState.isOpen}
          title={confirmState.title}
          message={confirmState.message}
          confirmLabel={confirmState.confirmLabel}
          onConfirm={confirmState.onConfirm}
          onCancel={() => setConfirmState(null)}
        />
      )}

      <AgentsDialog
        isOpen={agentsDialogOpen}
        onClose={() => setAgentsDialogOpen(false)}
        agentsData={agentsData}
        isLoading={isAgentsLoading}
      />
    </div>
  );
}