import React, { useState } from "react";
import { AlertTriangle, List, RefreshCw } from "lucide-react";
import type { ProjectRecord, Scope } from "@skilldock/shared";
import { useMcpList, useMcpAgents, useMcpAdd } from "../hooks/useMcp";
import { useProjects } from "../hooks/useProjects";
import { EmptyState } from "../components/ui/EmptyState";
import { McpServerList } from "../components/McpServerList";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";
import { AgentsDialog } from "../components/ui/AgentsDialog";
import { useLocale } from "../contexts/LocaleContext";
import { McpActionPanel } from "../components/McpActionPanel";
import { ScopeToggle } from "../components/ui/ScopeToggle";

export function Mcp({ onTaskStart }: { onTaskStart: (tid: string, title: string) => void }) {
  const [scope, setScope] = useState<Scope>("project");
  const { activeProject, activeProjectId } = useProjects();
  const {
    data: mcpListData,
    isLoading: isListLoading,
    isFetching: isListFetching,
    refetch: refetchList,
  } = useMcpList(scope, activeProjectId);
  const { data: agentsData, isLoading: isAgentsLoading } = useMcpAgents();
  const addMutation = useMcpAdd();
  const { t } = useLocale();

  const [confirmState, setConfirmState] = useState<{
    isOpen: boolean;
    title: string;
    message: string[];
    confirmLabel?: string;
    onConfirm: () => void;
  } | null>(null);

  const [agentsDialogOpen, setAgentsDialogOpen] = useState(false);

  // Form states
  const [target, setTarget] = useState("");
  const [name, setName] = useState("");
  const projectWriteDisabled = scope === "project" && activeProject?.status !== "valid";

  const projectContextMessage = (project: ProjectRecord | null) => {
    if (!project) return t("projects.loading");
    return t("projects.contextLine", {
      name: project.name,
      path: project.path,
    });
  };

  const handleAddMcp = (e: React.FormEvent) => {
    e.preventDefault();
    if (!target.trim() || projectWriteDisabled) return;

    setConfirmState({
      isOpen: true,
      title: t("mcp.addServerTitle"),
      message: [
        t("mcp.addServerMessage", { target }),
        name ? t("mcp.addServerName", { name }) : t("mcp.nameAutoGenerated"),
        projectContextMessage(activeProject),
        t("mcp.addServerScope", { scope })
      ],
      confirmLabel: t("mcp.addServerButton"),
      onConfirm: async () => {
        const res = await addMutation.mutateAsync({
          target,
          name: name || undefined,
          scope,
          projectId: activeProjectId ?? undefined,
        });
        onTaskStart(res.taskId, t("mcp.addingMcp", { target }));
        setTarget("");
        setName("");
        setConfirmState(null);
      }
    });
  };

  return (
    <div className="flex flex-col lg:flex-row gap-6 animate-in fade-in slide-in-from-bottom-4 duration-500 lg:h-[calc(100vh-13rem)] lg:min-h-[36rem] lg:overflow-hidden">
      <div className="flex-1 flex flex-col gap-6 min-w-0 lg:overflow-y-auto lg:pr-1">
        {addMutation.error && (
          <div className="p-4 rounded-xl bg-danger/10 border border-danger/30 text-danger text-sm flex items-center gap-3">
            <AlertTriangle size={16} />
            <span>{addMutation.error instanceof Error ? addMutation.error.message : t("common.operationFailed")}</span>
          </div>
        )}

        <header className="flex flex-col gap-4 sm:flex-row sm:items-center sm:gap-6">
          <div className="flex flex-wrap items-center gap-3">
            <ScopeToggle label={t("common.scope")} value={scope} onChange={setScope} />
            <button
              type="button"
              onClick={() => void refetchList()}
              disabled={isListFetching}
              aria-label={t("mcp.refreshAriaLabel", { scope })}
              className="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-xl border border-border bg-surface-800 px-4 py-2 text-xs font-bold transition-colors hover:bg-surface-600 disabled:cursor-not-allowed disabled:opacity-50"
            >
              <RefreshCw size={14} className={isListFetching ? "animate-spin" : ""} />
              {isListFetching ? t("mcp.refreshing") : t("mcp.refresh")}
            </button>
          </div>
        </header>

        <section className="space-y-4">
          <div className="flex items-center gap-3">
            <List size={20} className="text-accent-light" />
            <h3 className="font-bold tracking-tight uppercase text-xs tracking-widest text-text-muted">{t("mcp.configuredServers")}</h3>
          </div>

          {isListLoading ? (
            <div className="h-64 rounded-2xl bg-surface-800 border border-border animate-pulse" />
          ) : mcpListData ? (
            <McpServerList result={mcpListData} scope={scope} />
          ) : (
            <EmptyState title={t("mcp.noMcpConfig")} message={t("mcp.unableToFetch")} />
          )}
        </section>
      </div>

      <aside className="w-full lg:w-[360px] lg:self-stretch shrink-0 bg-surface-800 border border-border overflow-y-auto">
        <McpActionPanel
          activeProject={activeProject}
          projectWriteDisabled={projectWriteDisabled}
          onAddRequest={handleAddMcp}
          onViewAgents={() => setAgentsDialogOpen(true)}
          target={target}
          name={name}
          onTargetChange={setTarget}
          onNameChange={setName}
          isPending={addMutation.isPending}
        />
      </aside>

      {confirmState && (
        <ConfirmDialog
          isOpen={confirmState.isOpen}
          title={confirmState.title}
          message={confirmState.message}
          confirmLabel={confirmState.confirmLabel}
          onConfirm={confirmState.onConfirm}
          onCancel={() => setConfirmState(null)}
        />
      )}

      <AgentsDialog
        isOpen={agentsDialogOpen}
        onClose={() => setAgentsDialogOpen(false)}
        agentsData={agentsData}
        isLoading={isAgentsLoading}
      />
    </div>
  );
}
