export type Locale = "en-US" | "zh-CN";

export const DEFAULT_LOCALE: Locale = "en-US";

export const SUPPORTED_LOCALES: Locale[] = ["en-US", "zh-CN"];

export type TranslationKey =
  | "nav.overview"
  | "nav.skills"
  | "nav.mcp"
  | "nav.logs"
  | "nav.settings"
  | "sidebar.cliOperational"
  | "sidebar.cliDegraded"
  | "layout.switchToLightTheme"
  | "layout.switchToDarkTheme"
  | "overview.cliHealth"
  | "overview.systemStatus"
  | "overview.analyzing"
  | "overview.projectContext"
  | "overview.path"
  | "overview.runtime"
  | "overview.recentActivity"
  | "overview.noRecentOperations"
  | "overview.targetProject"
  | "common.scope"
  | "projects.project"
  | "projects.loading"
  | "projects.currentProject"
  | "projects.recentProjects"
  | "projects.noRecentProjects"
  | "projects.addLocalProject"
  | "projects.addLocalProjectHint"
  | "projects.projectPath"
  | "projects.validateAndAdd"
  | "projects.addProjectFailed"
  | "projects.loadFailed"
  | "projects.invalidCannotSelect"
  | "projects.invalidWriteDisabled"
  | "projects.contextLine"
  | "projects.removeRecent"
  | "projects.launchCannotRemove"
  | "projects.launchProject"
  | "projects.lastUsed"
  | "projects.status.valid"
  | "projects.status.missing"
  | "projects.status.not-directory"
  | "projects.status.inaccessible"
  | "skills.addSkill"
  | "skills.installFromPackage"
  | "skills.discoverSkills"
  | "skills.searchPlaceholder"
  | "skills.packagePlaceholder"
  | "skills.install"
  | "skills.installTitle"
  | "skills.installMessage"
  | "skills.installScope"
  | "skills.installDescription"
  | "skills.updateTitle"
  | "skills.updateMessage"
  | "skills.removeTitle"
  | "skills.removeMessage"
  | "skills.removeWarning"
  | "skills.noSkillsFound"
  | "skills.noSearchMatch"
  | "skills.noSkillsInstalled"
  | "skills.trySearchOrSwitch"
  | "skills.updateButton"
  | "skills.removeButton"
  | "skills.installedInSystem"
  | "skills.noAgents"
  | "skills.discoverTitle"
  | "skills.discoverPlaceholder"
  | "skills.discoverResults"
  | "skills.discoverInstallHint"
  | "skills.discoveryEmpty"
  | "skills.discoveryInstall"
  | "skills.searching"
  | "skills.searchError"
  | "mcp.addServerTitle"
  | "mcp.addServerMessage"
  | "mcp.addServerName"
  | "mcp.nameAutoGenerated"
  | "mcp.addServerScope"
  | "mcp.targetPlaceholder"
  | "mcp.namePlaceholder"
  | "mcp.addServerButton"
  | "mcp.addingMcp"
  | "mcp.configuredServers"
  | "mcp.noMcpConfig"
  | "mcp.unableToFetch"
  | "mcp.availableAgents"
  | "mcp.noAgentsFound"
  | "mcp.couldNotRetrieve"
  | "mcp.configuredServersDesc"
  | "mcp.availableAgentsDesc"
  | "mcp.noOutput"
  | "mcp.noErrors"
  | "logs.searchPlaceholder"
  | "logs.show"
  | "logs.records"
  | "logs.refreshHistory"
  | "logs.loadFailed"
  | "logs.noMatchingEntries"
  | "logs.standardOutput"
  | "logs.standardError"
  | "logs.empty"
  | "logs.exitCode"
  | "logs.duration"
  | "logs.timestamp"
  | "logs.source"
  | "logs.command"
  | "logs.args"
  | "logs.fullCommand"
  | "logs.noStdout"
  | "logs.noStderr"
  | "logs.project"
  | "logs.scope"
  | "settings.userPreferences"
  | "settings.defaultSkillsScope"
  | "settings.defaultMcpScope"
  | "settings.recentLogsLimit"
  | "settings.collapseRawOutput"
  | "settings.appearance"
  | "settings.appearanceDesc"
  | "settings.lightMode"
  | "settings.darkMode"
  | "settings.savePreferences"
  | "settings.systemContext"
  | "settings.configPath"
  | "settings.logsPath"
  | "settings.projectsPath"
  | "settings.cliCommands"
  | "settings.skillsLabel"
  | "settings.addMcpLabel"
  | "settings.securityNotice"
  | "taskDrawer.initializing"
  | "taskDrawer.lifecycle"
  | "taskDrawer.created"
  | "taskDrawer.started"
  | "taskDrawer.finished"
  | "taskDrawer.network"
  | "taskDrawer.transport"
  | "taskDrawer.finalResult"
  | "taskDrawer.project"
  | "taskDrawer.projectName"
  | "taskDrawer.projectPath"
  | "taskDrawer.scope"
  | "taskDrawer.console"
  | "taskDrawer.idleTitle"
  | "taskDrawer.idleDescription"
  | "dialog.confirm"
  | "dialog.cancel"
  | "error.retry"
  | "common.operationFailed"
  | "resultPanel.duration"
  | "resultPanel.emptyOutput"
  | "resultPanel.fullDetails"
  | "language.english"
  | "language.chinese"
  | "language.label"
  | "language.description";

const enUS: Record<TranslationKey, string> = {
  "nav.overview": "Overview",
  "nav.skills": "Skills",
  "nav.mcp": "MCP Center",
  "nav.logs": "Activity Logs",
  "nav.settings": "Settings",
  "sidebar.cliOperational": "Operational",
  "sidebar.cliDegraded": "Degraded",
  "layout.switchToLightTheme": "Switch to light theme",
  "layout.switchToDarkTheme": "Switch to dark theme",
  "overview.cliHealth": "CLI Health",
  "overview.systemStatus": "System Status",
  "overview.analyzing": "Analyzing...",
  "overview.projectContext": "Project Context",
  "overview.path": "Path",
  "overview.runtime": "Runtime",
  "overview.recentActivity": "Recent Activity",
  "overview.noRecentOperations": "No recent operations recorded.",
  "overview.targetProject": "Target Project",
  "common.scope": "Scope",
  "projects.project": "Project",
  "projects.loading": "Loading project",
  "projects.currentProject": "Current Project",
  "projects.recentProjects": "Recent Projects",
  "projects.noRecentProjects": "No recent projects yet.",
  "projects.addLocalProject": "Add Local Project",
  "projects.addLocalProjectHint": "Enter an existing local directory path. SkillDock will register it before use.",
  "projects.projectPath": "Project path",
  "projects.validateAndAdd": "Validate & Add",
  "projects.addProjectFailed": "Could not add this project.",
  "projects.loadFailed": "Could not load projects.",
  "projects.invalidCannotSelect": "This project is unavailable and cannot be selected.",
  "projects.invalidWriteDisabled": "Project-scope writes are disabled because the current project is unavailable.",
  "projects.contextLine": "Project: {{name}} ({{path}})",
  "projects.removeRecent": "Remove from recent projects",
  "projects.launchCannotRemove": "Launch project cannot be removed.",
  "projects.launchProject": "Launch project",
  "projects.lastUsed": "Last used {{time}}",
  "projects.status.valid": "valid",
  "projects.status.missing": "missing",
  "projects.status.not-directory": "not directory",
  "projects.status.inaccessible": "inaccessible",
  "skills.addSkill": "Add Skill",
  "skills.installFromPackage": "Install from package",
  "skills.discoverSkills": "Discover skills",
  "skills.searchPlaceholder": "Search skills...",
  "skills.packagePlaceholder": "Package name (e.g. vercel-labs/skills)",
  "skills.install": "Install",
  "skills.installTitle": "Install Skill",
  "skills.installMessage": "You are about to install package: {{package}}",
  "skills.installScope": "Scope: {{scope}}",
  "skills.installDescription": "This will download and configure the skill for the specified agents.",
  "skills.updateTitle": "Update Skill",
  "skills.updateMessage": "You are about to update skill: {{name}}",
  "skills.removeTitle": "Remove Skill",
  "skills.removeMessage": "You are about to remove skill: {{name}}",
  "skills.removeWarning": "This action cannot be undone.",
  "skills.noSkillsFound": "No Skills Found",
  "skills.noSearchMatch": "No skills match your search \"{{search}}\" in {{scope}} scope.",
  "skills.noSkillsInstalled": "You haven't installed any skills in the {{scope}} scope yet.",
  "skills.trySearchOrSwitch": "Try searching for a package above or switch to Global scope.",
  "skills.updateButton": "Update Skill",
  "skills.removeButton": "Remove Skill",
  "skills.installedInSystem": "Installed in system",
  "skills.noAgents": "No agents associated",
  "skills.discoverTitle": "Discover Skills",
  "skills.discoverPlaceholder": "Search for skills (e.g. vercel-labs)...",
  "skills.discoverResults": "Results for \"{{query}}\"",
  "skills.discoverInstallHint": "Click a package name to install it:",
  "skills.discoveryEmpty": "No skills found. Try another query.",
  "skills.discoveryInstall": "Install",
  "skills.searching": "Searching for \"{{query}}\"...",
  "skills.searchError": "Search failed. Please try again.",
  "mcp.addServerTitle": "Add MCP Server",
  "mcp.addServerMessage": "You are about to add MCP server: {{target}}",
  "mcp.addServerName": "Name: {{name}}",
  "mcp.nameAutoGenerated": "Name will be auto-generated",
  "mcp.addServerScope": "Scope: {{scope}}",
  "mcp.targetPlaceholder": "NPM package or URL",
  "mcp.namePlaceholder": "Custom name (optional)",
  "mcp.addServerButton": "Add Server",
  "mcp.addingMcp": "Adding MCP {{target}}",
  "mcp.configuredServers": "Configured Servers",
  "mcp.noMcpConfig": "No MCP Config",
  "mcp.unableToFetch": "Unable to fetch MCP list for this scope.",
  "mcp.availableAgents": "Available Agents",
  "mcp.noAgentsFound": "No Agents Found",
  "mcp.couldNotRetrieve": "Could not retrieve the agent list from the server.",
  "mcp.configuredServersDesc": "MCP configurations returned by `add-mcp list` for the current scope.",
  "mcp.availableAgentsDesc": "Agent targets recognized by `add-mcp list-agents`.",
  "mcp.noOutput": "No output",
  "mcp.noErrors": "No errors reported",
  "logs.searchPlaceholder": "Search logs...",
  "logs.show": "Show",
  "logs.records": "records",
  "logs.refreshHistory": "Refresh History",
  "logs.loadFailed": "Failed to load logs. Please try again.",
  "logs.noMatchingEntries": "No matching log entries found.",
  "logs.standardOutput": "Standard Output",
  "logs.standardError": "Standard Error",
  "logs.empty": "(empty)",
  "logs.exitCode": "Exit code",
  "logs.duration": "Duration",
  "logs.timestamp": "Timestamp",
  "logs.source": "Source",
  "logs.command": "Command",
  "logs.args": "Arguments",
  "logs.fullCommand": "Full command",
  "logs.noStdout": "No stdout output",
  "logs.noStderr": "No stderr output",
  "logs.project": "Project",
  "logs.scope": "Scope",
  "settings.userPreferences": "User Preferences",
  "settings.defaultSkillsScope": "Default Skills Scope",
  "settings.defaultMcpScope": "Default MCP Scope",
  "settings.recentLogsLimit": "Recent Logs Limit",
  "settings.collapseRawOutput": "Collapse raw output details by default",
  "settings.appearance": "Appearance",
  "settings.appearanceDesc": "Dark or light workspace theme",
  "settings.lightMode": "Light Mode",
  "settings.darkMode": "Dark Mode",
  "settings.savePreferences": "Save Security Preferences",
  "settings.systemContext": "System Context",
  "settings.configPath": "Configuration Path",
  "settings.logsPath": "Logs Path",
  "settings.projectsPath": "Projects Registry",
  "settings.cliCommands": "CLI Commands (Fixed)",
  "settings.skillsLabel": "Skills",
  "settings.addMcpLabel": "Add MCP",
  "settings.securityNotice": "Notice: SkillDock does not expose editable CLI paths or direct shell execution for security reasons.",
  "taskDrawer.initializing": "Initializing task environment...",
  "taskDrawer.lifecycle": "Lifecycle",
  "taskDrawer.created": "Created",
  "taskDrawer.started": "Started",
  "taskDrawer.finished": "Finished",
  "taskDrawer.network": "Network",
  "taskDrawer.transport": "Transport",
  "taskDrawer.finalResult": "Final Execution Result",
  "taskDrawer.project": "Project",
  "taskDrawer.projectName": "Name",
  "taskDrawer.projectPath": "Path",
  "taskDrawer.scope": "Scope",
  "taskDrawer.console": "Task Console",
  "taskDrawer.idleTitle": "No active task",
  "taskDrawer.idleDescription": "Run a Skills or MCP write operation to stream output here.",
  "dialog.confirm": "Confirm",
  "dialog.cancel": "Cancel",
  "error.retry": "Retry",
  "common.operationFailed": "Operation failed. Please try again.",
  "resultPanel.duration": "duration",
  "resultPanel.emptyOutput": "(empty output)",
  "resultPanel.fullDetails": "Full Details (stdout/stderr)",
  "language.english": "English",
  "language.chinese": "简体中文",
  "language.label": "Language",
  "language.description": "Interface language",
};

const zhCN: Record<TranslationKey, string> = {
  "nav.overview": "总览",
  "nav.skills": "Skills",
  "nav.mcp": "MCP 中心",
  "nav.logs": "活动日志",
  "nav.settings": "设置",
  "sidebar.cliOperational": "正常",
  "sidebar.cliDegraded": "异常",
  "layout.switchToLightTheme": "切换到浅色主题",
  "layout.switchToDarkTheme": "切换到深色主题",
  "overview.cliHealth": "CLI 状态",
  "overview.systemStatus": "系统状态",
  "overview.analyzing": "分析中...",
  "overview.projectContext": "项目上下文",
  "overview.path": "路径",
  "overview.runtime": "运行环境",
  "overview.recentActivity": "最近活动",
  "overview.noRecentOperations": "暂无操作记录。",
  "overview.targetProject": "目标项目",
  "common.scope": "范围",
  "projects.project": "项目",
  "projects.loading": "正在加载项目",
  "projects.currentProject": "当前项目",
  "projects.recentProjects": "最近项目",
  "projects.noRecentProjects": "暂无最近项目。",
  "projects.addLocalProject": "添加本地项目",
  "projects.addLocalProjectHint": "输入已存在的本地目录路径，SkillDock 会先注册后使用。",
  "projects.projectPath": "项目路径",
  "projects.validateAndAdd": "校验并添加",
  "projects.addProjectFailed": "无法添加该项目。",
  "projects.loadFailed": "无法加载项目列表。",
  "projects.invalidCannotSelect": "该项目不可用，不能切换到它。",
  "projects.invalidWriteDisabled": "当前项目不可用，已禁用项目范围写操作。",
  "projects.contextLine": "项目：{{name}}（{{path}}）",
  "projects.removeRecent": "从最近项目移除",
  "projects.launchCannotRemove": "启动项目不能移除。",
  "projects.launchProject": "启动项目",
  "projects.lastUsed": "最近使用 {{time}}",
  "projects.status.valid": "有效",
  "projects.status.missing": "缺失",
  "projects.status.not-directory": "非目录",
  "projects.status.inaccessible": "不可访问",
  "skills.addSkill": "添加 Skill",
  "skills.installFromPackage": "从包安装",
  "skills.discoverSkills": "发现 Skills",
  "skills.searchPlaceholder": "搜索 Skills...",
  "skills.packagePlaceholder": "包名（如 vercel-labs/skills）",
  "skills.install": "安装",
  "skills.installTitle": "安装 Skill",
  "skills.installMessage": "即将安装包：{{package}}",
  "skills.installScope": "范围：{{scope}}",
  "skills.installDescription": "将为指定 Agents 下载并配置该 Skill。",
  "skills.updateTitle": "更新 Skill",
  "skills.updateMessage": "即将更新 Skill：{{name}}",
  "skills.removeTitle": "移除 Skill",
  "skills.removeMessage": "即将移除 Skill：{{name}}",
  "skills.removeWarning": "此操作不可撤销。",
  "skills.noSkillsFound": "未找到 Skills",
  "skills.noSearchMatch": "在 {{scope}} 范围未找到匹配 \"{{search}}\" 的 Skills。",
  "skills.noSkillsInstalled": "尚未在 {{scope}} 范围安装任何 Skills。",
  "skills.trySearchOrSwitch": "尝试在上方搜索包，或切换到 Global 范围。",
  "skills.updateButton": "更新 Skill",
  "skills.removeButton": "移除 Skill",
  "skills.installedInSystem": "已安装于系统中",
  "skills.noAgents": "未关联 Agents",
  "skills.discoverTitle": "发现 Skills",
  "skills.discoverPlaceholder": "搜索 Skills（如 vercel-labs）...",
  "skills.discoverResults": "\"{{query}}\" 的搜索结果",
  "skills.discoverInstallHint": "点击包名进行安装：",
  "skills.discoveryEmpty": "未找到 Skills，尝试其他关键词。",
  "skills.discoveryInstall": "安装",
  "skills.searching": "正在搜索 \"{{query}}\"...",
  "skills.searchError": "搜索失败，请重试。",
  "mcp.addServerTitle": "添加 MCP Server",
  "mcp.addServerMessage": "即将添加 MCP Server：{{target}}",
  "mcp.addServerName": "名称：{{name}}",
  "mcp.nameAutoGenerated": "名称将自动生成",
  "mcp.addServerScope": "范围：{{scope}}",
  "mcp.targetPlaceholder": "NPM 包或 URL",
  "mcp.namePlaceholder": "自定义名称（可选）",
  "mcp.addServerButton": "添加 Server",
  "mcp.addingMcp": "添加 MCP {{target}}",
  "mcp.configuredServers": "已配置服务器",
  "mcp.noMcpConfig": "无 MCP 配置",
  "mcp.unableToFetch": "无法获取此范围的 MCP 列表。",
  "mcp.availableAgents": "可用 Agents",
  "mcp.noAgentsFound": "未找到 Agents",
  "mcp.couldNotRetrieve": "无法从服务器获取 Agents 列表。",
  "mcp.configuredServersDesc": "当前范围下 `add-mcp list` 返回的 MCP 配置结果。",
  "mcp.availableAgentsDesc": "`add-mcp list-agents` 识别出的可配置 agent 目标。",
  "mcp.noOutput": "无输出",
  "mcp.noErrors": "未报告错误",
  "logs.searchPlaceholder": "搜索日志...",
  "logs.show": "显示",
  "logs.records": "条记录",
  "logs.refreshHistory": "刷新历史",
  "logs.loadFailed": "加载日志失败，请重试。",
  "logs.noMatchingEntries": "未找到匹配的日志条目。",
  "logs.standardOutput": "标准输出",
  "logs.standardError": "标准错误",
  "logs.empty": "（空）",
  "logs.exitCode": "退出码",
  "logs.duration": "耗时",
  "logs.timestamp": "时间戳",
  "logs.source": "来源",
  "logs.command": "命令",
  "logs.args": "参数",
  "logs.fullCommand": "完整命令",
  "logs.noStdout": "无标准输出",
  "logs.noStderr": "无标准错误输出",
  "logs.project": "项目",
  "logs.scope": "范围",
  "settings.userPreferences": "用户偏好",
  "settings.defaultSkillsScope": "默认 Skills 范围",
  "settings.defaultMcpScope": "默认 MCP 范围",
  "settings.recentLogsLimit": "最近日志条数限制",
  "settings.collapseRawOutput": "默认折叠原始输出详情",
  "settings.appearance": "外观",
  "settings.appearanceDesc": "工作台明暗主题",
  "settings.lightMode": "浅色模式",
  "settings.darkMode": "深色模式",
  "settings.savePreferences": "保存安全偏好",
  "settings.systemContext": "系统上下文",
  "settings.configPath": "配置路径",
  "settings.logsPath": "日志路径",
  "settings.projectsPath": "项目注册表",
  "settings.cliCommands": "CLI 命令（固定）",
  "settings.skillsLabel": "Skills",
  "settings.addMcpLabel": "Add MCP",
  "settings.securityNotice": "注意：SkillDock 出于安全考虑，不提供可编辑的 CLI 路径或直接执行 shell 的功能。",
  "taskDrawer.initializing": "正在初始化任务环境...",
  "taskDrawer.lifecycle": "生命周期",
  "taskDrawer.created": "创建时间",
  "taskDrawer.started": "开始时间",
  "taskDrawer.finished": "完成时间",
  "taskDrawer.network": "网络",
  "taskDrawer.transport": "传输方式",
  "taskDrawer.finalResult": "最终执行结果",
  "taskDrawer.project": "项目",
  "taskDrawer.projectName": "名称",
  "taskDrawer.projectPath": "路径",
  "taskDrawer.scope": "范围",
  "taskDrawer.console": "任务控制台",
  "taskDrawer.idleTitle": "当前没有活动任务",
  "taskDrawer.idleDescription": "触发 Skills 或 MCP 写操作后，输出会持续显示在这里。",
  "dialog.confirm": "确认",
  "dialog.cancel": "取消",
  "error.retry": "重试",
  "common.operationFailed": "操作失败，请重试。",
  "resultPanel.duration": "耗时",
  "resultPanel.emptyOutput": "（无输出）",
  "resultPanel.fullDetails": "完整详情（stdout/stderr）",
  "language.english": "English",
  "language.chinese": "简体中文",
  "language.label": "语言",
  "language.description": "界面显示语言",
};

const dictionary: Record<Locale, Record<TranslationKey, string>> = {
  "en-US": enUS,
  "zh-CN": zhCN,
};

export function translate(locale: Locale, key: TranslationKey, params?: Record<string, string>): string {
  const text = dictionary[locale][key] ?? key;
  if (!params) return text;
  return Object.entries(params).reduce((acc, [k, v]) => {
    return acc.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), v);
  }, text);
}
