export type Locale = "en-US" | "zh-CN";

export const DEFAULT_LOCALE: Locale = "en-US";

export const SUPPORTED_LOCALES: Locale[] = ["en-US", "zh-CN"];

export type TranslationKey =
  | "nav.overview"
  | "nav.skills"
  | "nav.mcp"
  | "nav.logs"
  | "nav.settings"
  | "sidebar.cliOperational"
  | "sidebar.cliDegraded"
  | "layout.switchToLightTheme"
  | "layout.switchToDarkTheme"
  | "overview.cliHealth"
  | "overview.systemStatus"
  | "overview.analyzing"
  | "overview.projectContext"
  | "overview.path"
  | "overview.runtime"
  | "overview.recentActivity"
  | "overview.noRecentOperations"
  | "common.scope"
  | "skills.searchPlaceholder"
  | "skills.packagePlaceholder"
  | "skills.install"
  | "skills.installTitle"
  | "skills.installMessage"
  | "skills.installScope"
  | "skills.installDescription"
  | "skills.updateTitle"
  | "skills.updateMessage"
  | "skills.removeTitle"
  | "skills.removeMessage"
  | "skills.removeWarning"
  | "skills.noSkillsFound"
  | "skills.noSearchMatch"
  | "skills.noSkillsInstalled"
  | "skills.trySearchOrSwitch"
  | "skills.updateButton"
  | "skills.removeButton"
  | "skills.installedInSystem"
  | "skills.noAgents"
  | "mcp.addServerTitle"
  | "mcp.addServerMessage"
  | "mcp.addServerName"
  | "mcp.nameAutoGenerated"
  | "mcp.addServerScope"
  | "mcp.targetPlaceholder"
  | "mcp.namePlaceholder"
  | "mcp.addServerButton"
  | "mcp.addingMcp"
  | "mcp.configuredServers"
  | "mcp.noMcpConfig"
  | "mcp.unableToFetch"
  | "mcp.availableAgents"
  | "mcp.noAgentsFound"
  | "mcp.couldNotRetrieve"
  | "logs.searchPlaceholder"
  | "logs.show"
  | "logs.records"
  | "logs.refreshHistory"
  | "logs.loadFailed"
  | "logs.noMatchingEntries"
  | "logs.standardOutput"
  | "logs.standardError"
  | "logs.empty"
  | "settings.userPreferences"
  | "settings.defaultSkillsScope"
  | "settings.defaultMcpScope"
  | "settings.recentLogsLimit"
  | "settings.collapseRawOutput"
  | "settings.appearance"
  | "settings.appearanceDesc"
  | "settings.lightMode"
  | "settings.darkMode"
  | "settings.savePreferences"
  | "settings.systemContext"
  | "settings.configPath"
  | "settings.logsPath"
  | "settings.cliCommands"
  | "settings.skillsLabel"
  | "settings.addMcpLabel"
  | "settings.securityNotice"
  | "taskDrawer.initializing"
  | "taskDrawer.lifecycle"
  | "taskDrawer.created"
  | "taskDrawer.started"
  | "taskDrawer.finished"
  | "taskDrawer.network"
  | "taskDrawer.transport"
  | "taskDrawer.finalResult"
  | "dialog.confirm"
  | "dialog.cancel"
  | "error.retry"
  | "common.operationFailed"
  | "resultPanel.duration"
  | "resultPanel.emptyOutput"
  | "resultPanel.fullDetails"
  | "language.english"
  | "language.chinese"
  | "language.label"
  | "language.description";

const enUS: Record<TranslationKey, string> = {
  "nav.overview": "Overview",
  "nav.skills": "Skills",
  "nav.mcp": "MCP Center",
  "nav.logs": "Activity Logs",
  "nav.settings": "Settings",
  "sidebar.cliOperational": "Operational",
  "sidebar.cliDegraded": "Degraded",
  "layout.switchToLightTheme": "Switch to light theme",
  "layout.switchToDarkTheme": "Switch to dark theme",
  "overview.cliHealth": "CLI Health",
  "overview.systemStatus": "System Status",
  "overview.analyzing": "Analyzing...",
  "overview.projectContext": "Project Context",
  "overview.path": "Path",
  "overview.runtime": "Runtime",
  "overview.recentActivity": "Recent Activity",
  "overview.noRecentOperations": "No recent operations recorded.",
  "common.scope": "Scope",
  "skills.searchPlaceholder": "Search skills...",
  "skills.packagePlaceholder": "Package name (e.g. vercel-labs/skills)",
  "skills.install": "Install",
  "skills.installTitle": "Install Skill",
  "skills.installMessage": "You are about to install package: {{package}}",
  "skills.installScope": "Scope: {{scope}}",
  "skills.installDescription": "This will download and configure the skill for the specified agents.",
  "skills.updateTitle": "Update Skill",
  "skills.updateMessage": "You are about to update skill: {{name}}",
  "skills.removeTitle": "Remove Skill",
  "skills.removeMessage": "You are about to remove skill: {{name}}",
  "skills.removeWarning": "This action cannot be undone.",
  "skills.noSkillsFound": "No Skills Found",
  "skills.noSearchMatch": "No skills match your search \"{{search}}\" in {{scope}} scope.",
  "skills.noSkillsInstalled": "You haven't installed any skills in the {{scope}} scope yet.",
  "skills.trySearchOrSwitch": "Try searching for a package above or switch to Global scope.",
  "skills.updateButton": "Update Skill",
  "skills.removeButton": "Remove Skill",
  "skills.installedInSystem": "Installed in system",
  "skills.noAgents": "No agents associated",
  "mcp.addServerTitle": "Add MCP Server",
  "mcp.addServerMessage": "You are about to add MCP server: {{target}}",
  "mcp.addServerName": "Name: {{name}}",
  "mcp.nameAutoGenerated": "Name will be auto-generated",
  "mcp.addServerScope": "Scope: {{scope}}",
  "mcp.targetPlaceholder": "NPM package or URL",
  "mcp.namePlaceholder": "Custom name (optional)",
  "mcp.addServerButton": "Add Server",
  "mcp.addingMcp": "Adding MCP {{target}}",
  "mcp.configuredServers": "Configured Servers",
  "mcp.noMcpConfig": "No MCP Config",
  "mcp.unableToFetch": "Unable to fetch MCP list for this scope.",
  "mcp.availableAgents": "Available Agents",
  "mcp.noAgentsFound": "No Agents Found",
  "mcp.couldNotRetrieve": "Could not retrieve the agent list from the server.",
  "logs.searchPlaceholder": "Search logs...",
  "logs.show": "Show",
  "logs.records": "records",
  "logs.refreshHistory": "Refresh History",
  "logs.loadFailed": "Failed to load logs. Please try again.",
  "logs.noMatchingEntries": "No matching log entries found.",
  "logs.standardOutput": "Standard Output",
  "logs.standardError": "Standard Error",
  "logs.empty": "(empty)",
  "settings.userPreferences": "User Preferences",
  "settings.defaultSkillsScope": "Default Skills Scope",
  "settings.defaultMcpScope": "Default MCP Scope",
  "settings.recentLogsLimit": "Recent Logs Limit",
  "settings.collapseRawOutput": "Collapse raw output details by default",
  "settings.appearance": "Appearance",
  "settings.appearanceDesc": "Dark or light workspace theme",
  "settings.lightMode": "Light Mode",
  "settings.darkMode": "Dark Mode",
  "settings.savePreferences": "Save Security Preferences",
  "settings.systemContext": "System Context",
  "settings.configPath": "Configuration Path",
  "settings.logsPath": "Logs Path",
  "settings.cliCommands": "CLI Commands (Fixed)",
  "settings.skillsLabel": "Skills",
  "settings.addMcpLabel": "Add MCP",
  "settings.securityNotice": "Notice: SkillDock does not expose editable CLI paths or direct shell execution for security reasons.",
  "taskDrawer.initializing": "Initializing task environment...",
  "taskDrawer.lifecycle": "Lifecycle",
  "taskDrawer.created": "Created",
  "taskDrawer.started": "Started",
  "taskDrawer.finished": "Finished",
  "taskDrawer.network": "Network",
  "taskDrawer.transport": "Transport",
  "taskDrawer.finalResult": "Final Execution Result",
  "dialog.confirm": "Confirm",
  "dialog.cancel": "Cancel",
  "error.retry": "Retry",
  "common.operationFailed": "Operation failed. Please try again.",
  "resultPanel.duration": "duration",
  "resultPanel.emptyOutput": "(empty output)",
  "resultPanel.fullDetails": "Full Details (stdout/stderr)",
  "language.english": "English",
  "language.chinese": "简体中文",
  "language.label": "Language",
  "language.description": "Interface language",
};

const zhCN: Record<TranslationKey, string> = {
  "nav.overview": "总览",
  "nav.skills": "Skills",
  "nav.mcp": "MCP 中心",
  "nav.logs": "活动日志",
  "nav.settings": "设置",
  "sidebar.cliOperational": "正常",
  "sidebar.cliDegraded": "异常",
  "layout.switchToLightTheme": "切换到浅色主题",
  "layout.switchToDarkTheme": "切换到深色主题",
  "overview.cliHealth": "CLI 状态",
  "overview.systemStatus": "系统状态",
  "overview.analyzing": "分析中...",
  "overview.projectContext": "项目上下文",
  "overview.path": "路径",
  "overview.runtime": "运行环境",
  "overview.recentActivity": "最近活动",
  "overview.noRecentOperations": "暂无操作记录。",
  "common.scope": "范围",
  "skills.searchPlaceholder": "搜索 Skills...",
  "skills.packagePlaceholder": "包名（如 vercel-labs/skills）",
  "skills.install": "安装",
  "skills.installTitle": "安装 Skill",
  "skills.installMessage": "即将安装包：{{package}}",
  "skills.installScope": "范围：{{scope}}",
  "skills.installDescription": "将为指定 Agents 下载并配置该 Skill。",
  "skills.updateTitle": "更新 Skill",
  "skills.updateMessage": "即将更新 Skill：{{name}}",
  "skills.removeTitle": "移除 Skill",
  "skills.removeMessage": "即将移除 Skill：{{name}}",
  "skills.removeWarning": "此操作不可撤销。",
  "skills.noSkillsFound": "未找到 Skills",
  "skills.noSearchMatch": "在 {{scope}} 范围未找到匹配 \"{{search}}\" 的 Skills。",
  "skills.noSkillsInstalled": "尚未在 {{scope}} 范围安装任何 Skills。",
  "skills.trySearchOrSwitch": "尝试在上方搜索包，或切换到 Global 范围。",
  "skills.updateButton": "更新 Skill",
  "skills.removeButton": "移除 Skill",
  "skills.installedInSystem": "已安装于系统中",
  "skills.noAgents": "未关联 Agents",
  "mcp.addServerTitle": "添加 MCP Server",
  "mcp.addServerMessage": "即将添加 MCP Server：{{target}}",
  "mcp.addServerName": "名称：{{name}}",
  "mcp.nameAutoGenerated": "名称将自动生成",
  "mcp.addServerScope": "范围：{{scope}}",
  "mcp.targetPlaceholder": "NPM 包或 URL",
  "mcp.namePlaceholder": "自定义名称（可选）",
  "mcp.addServerButton": "添加 Server",
  "mcp.addingMcp": "添加 MCP {{target}}",
  "mcp.configuredServers": "已配置服务器",
  "mcp.noMcpConfig": "无 MCP 配置",
  "mcp.unableToFetch": "无法获取此范围的 MCP 列表。",
  "mcp.availableAgents": "可用 Agents",
  "mcp.noAgentsFound": "未找到 Agents",
  "mcp.couldNotRetrieve": "无法从服务器获取 Agents 列表。",
  "logs.searchPlaceholder": "搜索日志...",
  "logs.show": "显示",
  "logs.records": "条记录",
  "logs.refreshHistory": "刷新历史",
  "logs.loadFailed": "加载日志失败，请重试。",
  "logs.noMatchingEntries": "未找到匹配的日志条目。",
  "logs.standardOutput": "标准输出",
  "logs.standardError": "标准错误",
  "logs.empty": "（空）",
  "settings.userPreferences": "用户偏好",
  "settings.defaultSkillsScope": "默认 Skills 范围",
  "settings.defaultMcpScope": "默认 MCP 范围",
  "settings.recentLogsLimit": "最近日志条数限制",
  "settings.collapseRawOutput": "默认折叠原始输出详情",
  "settings.appearance": "外观",
  "settings.appearanceDesc": "工作台明暗主题",
  "settings.lightMode": "浅色模式",
  "settings.darkMode": "深色模式",
  "settings.savePreferences": "保存安全偏好",
  "settings.systemContext": "系统上下文",
  "settings.configPath": "配置路径",
  "settings.logsPath": "日志路径",
  "settings.cliCommands": "CLI 命令（固定）",
  "settings.skillsLabel": "Skills",
  "settings.addMcpLabel": "Add MCP",
  "settings.securityNotice": "注意：SkillDock 出于安全考虑，不提供可编辑的 CLI 路径或直接执行 shell 的功能。",
  "taskDrawer.initializing": "正在初始化任务环境...",
  "taskDrawer.lifecycle": "生命周期",
  "taskDrawer.created": "创建时间",
  "taskDrawer.started": "开始时间",
  "taskDrawer.finished": "完成时间",
  "taskDrawer.network": "网络",
  "taskDrawer.transport": "传输方式",
  "taskDrawer.finalResult": "最终执行结果",
  "dialog.confirm": "确认",
  "dialog.cancel": "取消",
  "error.retry": "重试",
  "common.operationFailed": "操作失败，请重试。",
  "resultPanel.duration": "耗时",
  "resultPanel.emptyOutput": "（无输出）",
  "resultPanel.fullDetails": "完整详情（stdout/stderr）",
  "language.english": "English",
  "language.chinese": "简体中文",
  "language.label": "语言",
  "language.description": "界面显示语言",
};

const dictionary: Record<Locale, Record<TranslationKey, string>> = {
  "en-US": enUS,
  "zh-CN": zhCN,
};

export function translate(locale: Locale, key: TranslationKey, params?: Record<string, string>): string {
  const text = dictionary[locale][key] ?? key;
  if (!params) return text;
  return Object.entries(params).reduce((acc, [k, v]) => {
    return acc.replace(new RegExp(`\\{\\{${k}\\}\\}`, "g"), v);
  }, text);
}
